# Generated by Django 5.1.2 on 2025-02-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_shop_delete_products_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phones', 'Phones'), ('speakers', 'Speakers'), ('laptops', 'Laptops'), ('footwears', 'Footwears'), ('appliances', 'Appliances'), ('clothing', 'Clothings')], default='appliances', max_length=20),
        ),
    ]
